import = ["~/.config/alacritty/colorschemes/tokyonight-storm.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 6

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"
title = "alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

[window.position]
x = 0
y = 0
